[[language]]
name = "python"
language-servers = ["pyright"]
auto-format = true
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }

[language-server.pyright]
command = "./.venv/Scripts/pyright-langserver.exe"
args = ["--stdio"]

[language-server.pyright.config]
python.pythonPath = "./.venv/Scripts/python.exe"

# --- JavaScript configuration ---
[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
auto-format = true
roots = ["package.json", ".git"]
formatter = { command = "prettier", args = ["--stdin-filepath", "file.js"] }

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

# --- Rust configuration ---
[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true
roots = ["Cargo.toml", ".git"]
formatter = { command = "rustfmt", args = ["--edition", "2021"] }

[language-server.rust-analyzer]
command = "rust-analyzer"

